'use client';

import { ActionButton, ConfirmDialog, DataTable, EmptyState, ErrorState, FormField, LoadingState, MetricCard, PageHeader, Panel, StatusBadge } from '@/components/accounting/AccountingUi';
import { useAccountingI18n } from '@/lib/accounting/i18n';
import { accountingApi } from '@/lib/api/accountingApi';
import { ArrowLeft, ArrowRight, CheckCircle2, Download, FileDown, RefreshCw, RotateCcw, XCircle } from 'lucide-react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useCallback, useEffect, useState } from 'react';
import { apiErrorMessage, collectionItems, enumName, formatDate, formatMoney, newCorrelationId, parseNumericIds, selectedLocale, todayIso } from '../../imports/_shared/accountingWorkspaceUtils';

const BATCH_STATUSES = ['', 'Prepared', 'Exported', 'Sent', 'Confirmed', 'PartiallyRejected', 'Rejected', 'Reversed'];
const PAYMENT_METHODS = ['', 'Bank', 'Cash', 'Hold', 'Mixed'];
const COPY = {
  ar: { eyebrow: 'تفاصيل دفعة السداد', back: 'دفعات السداد', refresh: 'تحديث', loadError: 'تعذر تحميل الدفعة.', actionError: 'تعذر إكمال الإجراء.', method: 'طريقة الدفع', lines: 'السطور', amount: 'المبلغ', confirmed: 'المؤكد', rejected: 'المرفوض', payroll: 'مسير الرواتب', file: 'ملف التصدير', export: 'تصدير', exportXlsx: 'تصدير XLSX', exportCsv: 'تصدير CSV', download: 'تنزيل الملف', linesTitle: 'سطور الدفعة', iqama: 'رقم الإقامة', lineId: 'معرّف السطر', iban: 'IBAN', housing: 'السكن', status: 'الحالة', reject: 'رفض السطر', reason: 'السبب', saveReject: 'تأكيد رفض السطر', cancel: 'إلغاء', confirmTitlePanel: 'تأكيد التسوية', confirmDescription: 'التأكيد يرحّل قيد السداد. يمكن تحديد سطور معينة أو تركها فارغة للمتاح كله.', settlementDate: 'تاريخ التسوية', postingProfile: 'ملف الترحيل', correlation: 'معرّف التتبع', idempotency: 'مفتاح عدم التكرار', selectedLines: 'معرّفات السطور', notes: 'ملاحظات', confirmSettlement: 'تأكيد التسوية', confirmQuestion: 'تأكيد التسوية وترحيل السداد؟', reverse: 'عكس الدفعة', reversalDate: 'تاريخ العكس', reverseQuestion: 'عكس دفعة السداد؟', reverseDescription: 'سينشئ الخادم مستنداً عكسياً ويعيد حالة السطور ذرياً.' },
  en: { eyebrow: 'Payment batch detail', back: 'Payment batches', refresh: 'Refresh', loadError: 'The payment batch could not be loaded.', actionError: 'The action could not be completed.', method: 'Payment method', lines: 'Lines', amount: 'Amount', confirmed: 'Confirmed', rejected: 'Rejected', payroll: 'Payroll run', file: 'Export file', export: 'Export', exportXlsx: 'Export XLSX', exportCsv: 'Export CSV', download: 'Download file', linesTitle: 'Payment lines', iqama: 'Iqama', lineId: 'Line ID', iban: 'IBAN', housing: 'Housing', status: 'Status', reject: 'Reject line', reason: 'Reason', saveReject: 'Confirm line rejection', cancel: 'Cancel', confirmTitlePanel: 'Confirm settlement', confirmDescription: 'Confirmation posts the payment journal. Select specific line IDs or leave empty for all eligible lines.', settlementDate: 'Settlement date', postingProfile: 'Posting profile', correlation: 'Correlation ID', idempotency: 'Idempotency key', selectedLines: 'Line IDs', notes: 'Notes', confirmSettlement: 'Confirm settlement', confirmQuestion: 'Confirm settlement and post payment?', reverse: 'Reverse payment batch', reversalDate: 'Reversal date', reverseQuestion: 'Reverse this payment batch?', reverseDescription: 'The server creates the reversal document and restores line state atomically.' },
};

function saveBlob(file, fallback) { if (!file?.blob || typeof window === 'undefined') return; const url = window.URL.createObjectURL(file.blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = file.fileName || fallback; document.body.appendChild(anchor); anchor.click(); anchor.remove(); window.URL.revokeObjectURL(url); }

export default function PaymentBatchDetailPage() {
  const { id } = useParams();
  const batchId = String(id);
  const { isRtl } = useAccountingI18n();
  const copy = isRtl ? COPY.ar : COPY.en;
  const locale = selectedLocale(isRtl);
  const BackIcon = isRtl ? ArrowRight : ArrowLeft;
  const [batch, setBatch] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [actionError, setActionError] = useState('');
  const [busy, setBusy] = useState('');
  const [confirmAction, setConfirmAction] = useState('');
  const [selectedLine, setSelectedLine] = useState(null);
  const [rejectReason, setRejectReason] = useState('');
  const [confirmForm, setConfirmForm] = useState({ settlementDate: todayIso(), postingProfileCode: 'PAYROLL-PAYMENT', correlationId: newCorrelationId('payment'), idempotencyKey: newCorrelationId('settlement'), lineIds: '', notes: '' });
  const [reverseForm, setReverseForm] = useState({ reversalDate: todayIso(), reason: '', correlationId: newCorrelationId('payment-reversal'), idempotencyKey: newCorrelationId('reverse') });
  const load = useCallback(async () => { setLoading(true); setError(''); try { setBatch(await accountingApi.payments.get(batchId)); } catch (requestError) { setError(apiErrorMessage(requestError, copy.loadError)); } finally { setLoading(false); } }, [batchId, copy.loadError]);
  useEffect(() => { load(); }, [load]);
  const action = async (name, task, { reload = true } = {}) => { if (busy) return null; setBusy(name); setActionError(''); try { const result = await task(); if (reload) await load(); return result; } catch (requestError) { setActionError(apiErrorMessage(requestError, copy.actionError)); return null; } finally { setBusy(''); } };
  const exportBatch = (format) => action(`export-${format}`, () => accountingApi.payments.exportBatch(batchId, { format }));
  const downloadExport = async () => { const file = await action('download', () => accountingApi.files.download(batch.exportFileId), { reload: false }); if (file) saveBlob(file, `payment-batch-${batchId}`); };
  const rejectLine = async (event) => { event.preventDefault(); const result = await action('reject-line', () => accountingApi.payments.rejectLine(batchId, selectedLine.id, { reason: rejectReason.trim() })); if (result) { setSelectedLine(null); setRejectReason(''); } };
  const confirmLifecycle = async () => {
    const isConfirm = confirmAction === 'confirm';
    const payload = isConfirm ? { settlementDate: confirmForm.settlementDate, postingProfileCode: confirmForm.postingProfileCode.trim(), idempotencyKey: confirmForm.idempotencyKey.trim(), correlationId: confirmForm.correlationId.trim(), lineIds: confirmForm.lineIds.trim() ? parseNumericIds(confirmForm.lineIds) : null, notes: confirmForm.notes.trim() || null } : { reversalDate: reverseForm.reversalDate, reason: reverseForm.reason.trim(), idempotencyKey: reverseForm.idempotencyKey.trim(), correlationId: reverseForm.correlationId.trim() };
    const result = await action(confirmAction, () => isConfirm ? accountingApi.payments.confirmBatch(batchId, payload) : accountingApi.payments.reverseBatch(batchId, payload)); if (result) setConfirmAction('');
  };
  const status = enumName(batch?.status, BATCH_STATUSES);
  const lines = collectionItems(batch?.lines);
  const total = lines.reduce((sum, line) => sum + Number(line.amount || 0), 0);
  const confirmedAmount = lines.filter((line) => line.isConfirmed).reduce((sum, line) => sum + Number(line.amount || 0), 0);
  const lineColumns = [{ key: 'id', header: copy.lineId, render: (item) => <span dir="ltr" className="font-mono text-xs">{item.id}</span> }, { key: 'riderIqamaNo', header: copy.iqama, render: (item) => <span dir="ltr">{item.riderIqamaNo}</span> }, { key: 'method', header: copy.method, render: (item) => enumName(item.method, PAYMENT_METHODS) }, { key: 'amount', header: copy.amount, align: 'end', render: (item) => formatMoney(item.amount, locale) }, { key: 'ibanSnapshot', header: copy.iban, render: (item) => <span dir="ltr" className="font-mono text-xs">{item.ibanSnapshot || '—'}</span> }, { key: 'housingId', header: copy.housing, render: (item) => item.housingId || '—' }, { key: 'status', header: copy.status, render: (item) => <StatusBadge status={item.isConfirmed ? 'Confirmed' : item.rejectionReason ? 'Rejected' : 'Prepared'} label={item.rejectionReason || undefined} /> }, { key: 'action', header: '', render: (item) => !item.isConfirmed && !item.rejectionReason ? <ActionButton size="sm" variant="danger" icon={XCircle} onClick={() => setSelectedLine(item)}>{copy.reject}</ActionButton> : null }];
  if (loading) return <LoadingState />;
  if (error || !batch) return <ErrorState description={error || copy.loadError} onRetry={load} />;
  return <div className="space-y-5" dir={isRtl ? 'rtl' : 'ltr'}><PageHeader eyebrow={copy.eyebrow} title={batch.batchNumber || batch.id} description={<Link className="font-mono text-xs text-blue-700 hover:underline" href={`/accountant/payroll/${batch.riderPayrollRunId}`} dir="ltr">{batch.riderPayrollRunId}</Link>} meta={<StatusBadge status={status} />} actions={<div className="flex flex-wrap gap-2"><Link href="/accountant/payments" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-300 bg-white px-4 text-sm font-semibold text-slate-700 hover:bg-slate-50"><BackIcon size={17} />{copy.back}</Link><ActionButton variant="secondary" icon={RefreshCw} onClick={load}>{copy.refresh}</ActionButton></div>} />{actionError && <ErrorState description={actionError} compact />}<section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label={copy.method} value={enumName(batch.method, PAYMENT_METHODS)} /><MetricCard label={copy.lines} value={lines.length} /><MetricCard label={copy.amount} value={formatMoney(total, locale)} /><MetricCard label={copy.confirmed} value={formatMoney(confirmedAmount, locale)} tone="success" /><MetricCard label={copy.rejected} value={lines.filter((line) => line.rejectionReason).length} tone="warning" /></section>
    <Panel title={copy.export} actions={<div className="flex flex-wrap gap-2"><ActionButton variant="secondary" icon={FileDown} loading={busy === 'export-xlsx'} onClick={() => exportBatch('xlsx')}>{copy.exportXlsx}</ActionButton><ActionButton variant="secondary" icon={FileDown} loading={busy === 'export-csv'} onClick={() => exportBatch('csv')}>{copy.exportCsv}</ActionButton>{batch.exportFileId && <ActionButton icon={Download} loading={busy === 'download'} onClick={downloadExport}>{copy.download}</ActionButton>}</div>}>{batch.exportFileId ? <p className="font-mono text-sm text-slate-700" dir="ltr">{batch.exportFileId}</p> : <EmptyState title={copy.file} compact />}</Panel>
    <Panel title={copy.linesTitle}><DataTable columns={lineColumns} data={lines} rowKey="id" /></Panel>
    {selectedLine && <Panel title={`${copy.reject}: ${selectedLine.riderIqamaNo}`}><form className="grid gap-4 md:grid-cols-[1fr_auto]" onSubmit={rejectLine}><FormField label={copy.reason} required><input required value={rejectReason} onChange={(event) => setRejectReason(event.target.value)} /></FormField><div className="flex items-end gap-2"><ActionButton variant="secondary" onClick={() => setSelectedLine(null)}>{copy.cancel}</ActionButton><ActionButton variant="danger" type="submit" loading={busy === 'reject-line'}>{copy.saveReject}</ActionButton></div></form></Panel>}
    {!['Confirmed', 'Reversed', 'Rejected'].includes(status) && <Panel title={copy.confirmTitlePanel} description={copy.confirmDescription}><form className="grid gap-4 md:grid-cols-2 xl:grid-cols-3" onSubmit={(event) => { event.preventDefault(); setConfirmAction('confirm'); }}><FormField label={copy.settlementDate} required><input type="date" required value={confirmForm.settlementDate} onChange={(event) => setConfirmForm((current) => ({ ...current, settlementDate: event.target.value }))} /></FormField><FormField label={copy.postingProfile} required><input dir="ltr" required value={confirmForm.postingProfileCode} onChange={(event) => setConfirmForm((current) => ({ ...current, postingProfileCode: event.target.value }))} /></FormField><FormField label={copy.selectedLines}><input dir="ltr" placeholder="101, 102" value={confirmForm.lineIds} onChange={(event) => setConfirmForm((current) => ({ ...current, lineIds: event.target.value }))} /></FormField><FormField label={copy.correlation} required><input dir="ltr" required value={confirmForm.correlationId} onChange={(event) => setConfirmForm((current) => ({ ...current, correlationId: event.target.value }))} /></FormField><FormField label={copy.idempotency} required><input dir="ltr" required value={confirmForm.idempotencyKey} onChange={(event) => setConfirmForm((current) => ({ ...current, idempotencyKey: event.target.value }))} /></FormField><FormField label={copy.notes}><input value={confirmForm.notes} onChange={(event) => setConfirmForm((current) => ({ ...current, notes: event.target.value }))} /></FormField><div className="xl:col-span-3 flex justify-end"><ActionButton type="submit" icon={CheckCircle2}>{copy.confirmSettlement}</ActionButton></div></form></Panel>}
    {['Confirmed', 'PartiallyRejected'].includes(status) && <Panel title={copy.reverse}><form className="grid gap-4 md:grid-cols-2 xl:grid-cols-4" onSubmit={(event) => { event.preventDefault(); setConfirmAction('reverse'); }}><FormField label={copy.reversalDate} required><input type="date" required value={reverseForm.reversalDate} onChange={(event) => setReverseForm((current) => ({ ...current, reversalDate: event.target.value }))} /></FormField><FormField label={copy.reason} required><input required value={reverseForm.reason} onChange={(event) => setReverseForm((current) => ({ ...current, reason: event.target.value }))} /></FormField><FormField label={copy.correlation} required><input dir="ltr" required value={reverseForm.correlationId} onChange={(event) => setReverseForm((current) => ({ ...current, correlationId: event.target.value }))} /></FormField><FormField label={copy.idempotency} required><input dir="ltr" required value={reverseForm.idempotencyKey} onChange={(event) => setReverseForm((current) => ({ ...current, idempotencyKey: event.target.value }))} /></FormField><div className="xl:col-span-4 flex justify-end"><ActionButton variant="danger" type="submit" icon={RotateCcw}>{copy.reverse}</ActionButton></div></form></Panel>}
    <ConfirmDialog open={Boolean(confirmAction)} title={confirmAction === 'confirm' ? copy.confirmQuestion : copy.reverseQuestion} description={confirmAction === 'confirm' ? copy.confirmDescription : copy.reverseDescription} confirmLabel={confirmAction === 'confirm' ? copy.confirmSettlement : copy.reverse} cancelLabel={copy.cancel} tone={confirmAction === 'confirm' ? 'primary' : 'danger'} loading={busy === confirmAction} onConfirm={confirmLifecycle} onCancel={() => setConfirmAction('')} />
  </div>;
}
